### ISSUE TITLE
REI Instability since updating to v1.6

### ISSUE THREAD

**Issue by InFuRiTy** [LunaPixelStudios/Prominence#20]
### Describe the Bug

REI is displaying some really weird/bizarre behavior on otherwise normal player actions since i've updated to v1.6

For example:

1. Random freezes/lag spikes on recipe lookups/uses (no pattern has been observed till now)
2. Causes the game to randomly crash upon Favoring an item, right clicking a crafting table and switching between recipe tabs very fast.
3. Game freezing/lagging because it's not done initializing after joining a server/world. (image provided)
4. REI refuses to search at all with any normal text input until you manually reload it's plugins through the settings.

I have tried deleting/reinstalling the pack many times.
Removed any extra mods I've added to test it out.
Reallocated different amounts of RAM.
All exterior software is up to date. eg. Java, modloader, launcher etc.

Before updating to v1.6, the pack was running with no issues in the server I'm playing.
Other players experience REI instability to various degrees too in our server.

### Reproduction Steps

1.Launch game
2.Load into a server/world
3.Observe REI's behavior

### Screenshots and Videos

![2023-05-26_01 20 28](https://github.com/LunaPixelStudios/Prominence/assets/95109357/1a3a775c-4c7e-4bc5-b100-565456677414)

### Crash Report or Log

https://pastebin.com/xPaLEsie

### Operating System

Windows 10 Pro

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

Prominence v1.6

### Optifine

No

### Other Mods

Inventory HUD+ 3.4.7 for 1.19.2 - Fabric

I use it for inventory and HUD elements management  on screen to fit my playstyle.

**Comment by jmadarg** [comment]
Can you try disabling Async Search on the REI configs?

**Comment by InFuRiTy** [comment]
> Can you try disabling Async Search on the REI configs?

I did. It feels more responsive now. The initialization messages still appear  but it does load way faster now.
About any related crashes though.. i'll have to play a bit more to test this out. For the moment it seems stable.

I don't get it. What changed? In v1.5 REI was working normally with no issues!

**Comment by InFuRiTy** [comment]
I'm starting to think this isn't REI's fault at all rn.

My game just crashed again while opening a chest that i've opened a million times before.
Here's the new log: https://pastebin.com/Hchgvu97

Am i going crazy? What is happening?

**Comment by jmadarg** [comment]
I don't know much about the details, but as far as I know there is a conflict between REI and modern fix, but should be solved soon. About your latest crash, not sure what could have happened; were you able to open the chest afterwards?

**Comment by InFuRiTy** [comment]
Yes chest opens like normal again.

It was a complete random event that happens usually with right-clicking into a block's UI or using a keybind but it's more frequent 
when REI is involved!

I just hope the next update fixes all these issues because the pack is really awesome to play and i don't wanna drop it!!
Keep up the good work!!

**Comment by InFuRiTy** [comment]
> I don't know much about the details, but as far as I know there is a conflict between REI and modern fix, but should be solved soon. About your latest crash, not sure what could have happened; were you able to open the chest afterwards?

I can confirm it's an issue with ModernFix. I removed the mod from my client, then joined my server and played for like 4 hours straight without a single hiccup!!  REI Initialization lag still happens but it's manageable!!

**Comment by InFuRiTy** [comment]
Update 3 on the issue...

It happened again when i opened my inventory in the server

And this time was without the MF mod and the Async Search off..
i'm at a loss here..
[crash-2023-05-28_19.27.15-client.txt](https://github.com/LunaPixelStudios/Prominence/files/11585154/crash-2023-05-28_19.27.15-client.txt)

**Comment by nvb-uy** [comment]
fixed in 1.6.1
